
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Search, EditPen, Delete } from '@element-plus/icons-vue'
import { adminCategoryApi } from '@/api'
import type { Category, PageData } from '@/types'
import { dateTime } from '@/utils'
const data=ref<PageData<Category>>({records:[],current:1,size:10,total:0,pages:0});const query=reactive({page:1,size:10,keyword:'',status:undefined as number|undefined});const dialog=ref(false);const saving=ref(false);const editId=ref<number>();const form=reactive({categoryName:'',categoryImage:'',description:'',sortNo:0,status:1})
const load=async(page=query.page)=>{query.page=page;data.value=await adminCategoryApi.page(query)};onMounted(load)
const open=(item?:Category)=>{editId.value=item?.id;Object.assign(form,item?{categoryName:item.categoryName,categoryImage:item.categoryImage||'',description:item.description||'',sortNo:item.sortNo,status:item.status}:{categoryName:'',categoryImage:'',description:'',sortNo:data.value.records.length+1,status:1});dialog.value=true}
const save=async()=>{if(!form.categoryName)return ElMessage.warning('请输入分类名称');saving.value=true;try{if(editId.value)await adminCategoryApi.update(editId.value,form);else await adminCategoryApi.add(form);ElMessage.success('保存成功');dialog.value=false;await load()}finally{saving.value=false}}
const remove=async(item:Category)=>{await ElMessageBox.confirm(`确认删除分类“${item.categoryName}”吗？若分类下仍有药品，系统会拒绝删除。`,'删除分类',{type:'warning'});await adminCategoryApi.remove(item.id);ElMessage.success('已删除');await load()}
const toggle=async(item:Category)=>{await adminCategoryApi.status(item.id,item.status?0:1);ElMessage.success('状态已更新');await load(data.value.current)}
</script>
<template><div><div class="admin-page-head"><div><span class="eyebrow">CATEGORY MANAGEMENT</span><h1>药品分类</h1><p>维护前台分类入口、排序与启用状态。</p></div><el-button type="primary" :icon="Plus" @click="open()">新增分类</el-button></div><section class="control-card table-card"><div class="filter-row"><el-input v-model="query.keyword" placeholder="搜索分类名称" :prefix-icon="Search" clearable @keyup.enter="load(1)" @clear="load(1)"/><el-select v-model="query.status" placeholder="全部状态" clearable @change="load(1)"><el-option label="启用" :value="1"/><el-option label="停用" :value="0"/></el-select><el-button type="primary" @click="load(1)">查询</el-button><el-button @click="Object.assign(query,{keyword:'',status:undefined});load(1)">重置</el-button></div><el-table :data="data.records" stripe><el-table-column label="分类" min-width="210"><template #default="{row}"><div class="category-cell"><img v-if="row.categoryImage" :src="row.categoryImage"/><span v-else>药</span><div><b>{{row.categoryName}}</b><small>{{row.description||'暂无分类描述'}}</small></div></div></template></el-table-column><el-table-column prop="sortNo" label="排序" width="85"/><el-table-column label="状态" width="110"><template #default="{row}"><el-switch :model-value="row.status===1" @change="toggle(row)"/></template></el-table-column><el-table-column label="更新时间" width="170"><template #default="{row}">{{dateTime(row.updateTime)}}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button text type="primary" :icon="EditPen" @click="open(row)">编辑</el-button><el-button text type="danger" :icon="Delete" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination background layout="total, prev, pager, next" :current-page="data.current" :page-size="data.size" :total="data.total" @current-change="load"/></div></section><el-dialog v-model="dialog" :title="editId?'编辑分类':'新增分类'" width="min(520px,92%)"><el-form label-position="top"><el-form-item label="分类名称" required><el-input v-model="form.categoryName" maxlength="50"/></el-form-item><el-form-item label="分类图标地址"><el-input v-model="form.categoryImage" placeholder="例如：/images/category/cold.svg"/></el-form-item><el-form-item label="分类说明"><el-input v-model="form.description" type="textarea" :rows="3" maxlength="255"/></el-form-item><div class="form-two"><el-form-item label="排序号"><el-input-number v-model="form.sortNo" :min="0"/></el-form-item><el-form-item label="启用状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" active-text="启用" inactive-text="停用"/></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.eyebrow{font-size:11px;color:#1677ff;letter-spacing:2px;font-weight:700}.admin-page-head h1{font-size:27px;margin:6px 0}.admin-page-head p{margin:0;color:#8491a4;font-size:13px}.filter-row .el-input{width:260px}.filter-row .el-select{width:130px}.category-cell{display:flex;align-items:center;gap:10px}.category-cell img,.category-cell>span{width:38px;height:38px;border-radius:11px;background:#eaf5ff;object-fit:cover;display:grid;place-items:center;color:#1677ff}.category-cell b,.category-cell small{display:block}.category-cell b{font-size:13px}.category-cell small{margin-top:4px;font-size:11px;color:#8b98aa}.form-two{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:650px){.filter-row .el-input{width:100%;flex-basis:100%}.form-two{grid-template-columns:1fr}}</style>
