
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Warning, Box } from '@element-plus/icons-vue'
import { adminMedicineApi } from '@/api'
import type { Medicine, PageData } from '@/types'
import { money } from '@/utils'
const data=ref<PageData<Medicine>>({records:[],current:1,size:10,total:0,pages:0});const loading=ref(false);const load=async(page=1)=>{loading.value=true;try{data.value=await adminMedicineApi.low({page,size:10})}finally{loading.value=false}};onMounted(load)
</script>
<template><div><div class="admin-page-head"><div><span class="eyebrow">STOCK ALERT</span><h1>库存预警</h1><p>当前库存小于或等于预警阈值的上架药品。</p></div><el-button @click="load(data.current)">刷新预警</el-button></div><section class="alert-banner"><span><el-icon><Warning/></el-icon></span><div><b>发现 {{data.total}} 项库存需要关注</b><p>建议及时补货，避免用户下单时出现缺货。</p></div></section><section class="control-card inventory-list" v-loading="loading"><article v-for="m in data.records" :key="m.id" class="inventory-row"><div class="inventory-img"><img v-if="m.imageUrl" :src="m.imageUrl"/><span v-else>药</span></div><div class="inventory-main"><span>{{m.categoryName}}</span><h3>{{m.medicineName}}</h3><p>{{m.description||'暂无商品说明'}}</p></div><div class="inventory-stock"><b :class="{out:m.stock<=0}">{{m.stock}}</b><span>当前库存 / 预警 {{m.warningStock}}</span></div><strong>{{money(m.price)}}</strong><el-button type="primary" plain @click="$router.push('/admin/medicines')"><el-icon><Box/></el-icon>去补货</el-button></article><div v-if="!data.records.length&&!loading" class="no-alert"><el-icon><Warning/></el-icon><h3>库存状态良好</h3><p>当前没有需要预警的药品。</p></div></section><div class="pagination"><el-pagination background layout="total, prev, pager, next" :current-page="data.current" :page-size="data.size" :total="data.total" @current-change="load"/></div></div></template>
<style scoped>.eyebrow{font-size:11px;color:#1677ff;letter-spacing:2px;font-weight:700}.admin-page-head h1{font-size:27px;margin:6px 0}.admin-page-head p{margin:0;color:#8491a4;font-size:13px}.alert-banner{display:flex;align-items:center;gap:14px;padding:18px;background:linear-gradient(135deg,#fff4e8,#fffaf2);border:1px solid #ffe0ba;border-radius:14px;margin-bottom:18px}.alert-banner>span{width:42px;height:42px;border-radius:13px;background:#fff0d9;color:#ff8a34;display:grid;place-items:center;font-size:21px}.alert-banner b{font-size:15px;color:#a55b16}.alert-banner p{font-size:12px;color:#a67f5a;margin:5px 0 0}.inventory-list{padding:0;overflow:hidden}.inventory-row{display:grid;grid-template-columns:52px 1fr 155px 92px 90px;align-items:center;gap:15px;padding:16px 20px;border-bottom:1px solid #eef2f6}.inventory-row:last-child{border:0}.inventory-img{width:48px;height:48px;background:#eaf5ff;border-radius:12px;overflow:hidden;display:grid;place-items:center;color:#1677ff}.inventory-img img{width:100%;height:100%;object-fit:cover}.inventory-main span{font-size:11px;color:#1677ff}.inventory-main h3{font-size:14px;margin:4px 0}.inventory-main p{font-size:11px;color:#8c99aa;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:450px}.inventory-stock{text-align:center}.inventory-stock b{display:block;color:#ff8a34;font-size:24px}.inventory-stock b.out{color:#f04438}.inventory-stock span{font-size:10px;color:#96a3b4}.inventory-row>strong{color:#ff6d2c}.no-alert{text-align:center;padding:75px;color:#8190a4}.no-alert .el-icon{font-size:44px;color:#58ca9e}.no-alert h3{color:#4f6076;font-size:16px}.no-alert p{font-size:12px}.pagination{margin-top:18px;display:flex;justify-content:flex-end}@media(max-width:750px){.inventory-row{grid-template-columns:48px 1fr 70px;gap:10px;padding:14px}.inventory-stock{grid-column:2;text-align:left}.inventory-row>strong{grid-column:3;grid-row:1}.inventory-row>.el-button{grid-column:3;grid-row:2}.inventory-main p{max-width:180px}}</style>
