
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { Monitor, House, UserFilled, ArrowRight } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
const store=useUserStore();const router=useRouter()
</script>
<template><div class="admin-profile"><section class="admin-profile-banner"><el-avatar :size="78">{{store.user?.nickname?.slice(0,1)||'管'}}</el-avatar><div><span>药品管理员</span><h1>{{store.user?.nickname}}</h1><p>账号：{{store.user?.username}}　{{store.user?.phone||'未绑定手机号'}}</p></div></section><section class="profile-tips"><h2>管理员工作台</h2><button @click="router.push('/admin/dashboard')"><span><el-icon><Monitor/></el-icon></span><div><b>运营控制中心</b><small>查看订单、销售额、库存预警与排行榜</small></div><el-icon><ArrowRight/></el-icon></button><button @click="router.push('/home')"><span><el-icon><House/></el-icon></span><div><b>前台商城</b><small>切换到普通用户视角浏览商城</small></div><el-icon><ArrowRight/></el-icon></button><button @click="router.push('/admin/users')"><span><el-icon><UserFilled/></el-icon></span><div><b>用户管理</b><small>查看注册用户与账号启用状态</small></div><el-icon><ArrowRight/></el-icon></button></section></div></template>
<style scoped>.admin-profile-banner{background:linear-gradient(135deg,#0b4f9c,#1677ff);padding:35px;border-radius:18px;color:#fff;display:flex;align-items:center;gap:18px}.admin-profile-banner .el-avatar{background:rgba(255,255,255,.16);color:#fff;border:1px solid rgba(255,255,255,.3);font-size:30px}.admin-profile-banner span{font-size:12px;color:#c6e7ff}.admin-profile-banner h1{font-size:27px;margin:6px 0}.admin-profile-banner p{font-size:13px;margin:0;color:#d9efff}.profile-tips{max-width:760px;margin:25px auto}.profile-tips h2{font-size:17px;margin-bottom:13px}.profile-tips button{width:100%;border:1px solid #e6edf7;background:#fff;border-radius:14px;padding:17px;display:flex;align-items:center;gap:14px;text-align:left;margin-bottom:11px;cursor:pointer;transition:.2s}.profile-tips button:hover{border-color:#b9d8ff;box-shadow:0 10px 22px rgba(20,72,128,.09);transform:translateY(-2px)}.profile-tips button>span{width:42px;height:42px;background:#eaf5ff;color:#1677ff;display:grid;place-items:center;border-radius:13px;font-size:19px}.profile-tips div{flex:1}.profile-tips b,.profile-tips small{display:block}.profile-tips b{font-size:14px;color:#33455c}.profile-tips small{font-size:12px;color:#8795a7;margin-top:5px}.profile-tips button>.el-icon{color:#96a8bd}</style>
