
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Search, EditPen, Delete } from '@element-plus/icons-vue'
import { riderApi } from '@/api'
import type { PageData, Rider } from '@/types'
import { dateTime } from '@/utils'
const data=ref<PageData<Rider>>({records:[],current:1,size:10,total:0,pages:0});const query=reactive({page:1,size:10,keyword:'',status:undefined as number|undefined});const dialog=ref(false);const saving=ref(false);const editId=ref<number>();const form=reactive({riderName:'',phone:'',status:1,remark:''})
const load=async(page=query.page)=>{query.page=page;data.value=await riderApi.page(query)};onMounted(load)
const open=(r?:Rider)=>{editId.value=r?.id;Object.assign(form,r?{riderName:r.riderName,phone:r.phone,status:r.status,remark:r.remark||''}:{riderName:'',phone:'',status:1,remark:''});dialog.value=true}
const save=async()=>{if(!form.riderName||!form.phone)return ElMessage.warning('请填写骑手姓名和手机号');saving.value=true;try{if(editId.value)await riderApi.update(editId.value,form);else await riderApi.add(form);ElMessage.success('保存成功');dialog.value=false;await load()}finally{saving.value=false}}
const toggle=async(r:Rider)=>{await riderApi.status(r.id,r.status?0:1);ElMessage.success('状态已更新');await load(data.value.current)}
const remove=async(r:Rider)=>{await ElMessageBox.confirm(`确认删除骑手“${r.riderName}”吗？配送中的订单会阻止删除。`,'删除骑手',{type:'warning'});await riderApi.remove(r.id);ElMessage.success('已删除');await load()}
</script>
<template><div><div class="admin-page-head"><div><span class="eyebrow">RIDER MANAGEMENT</span><h1>骑手管理</h1><p>维护派单时可选择的配送骑手，不提供独立骑手登录端。</p></div><el-button type="primary" :icon="Plus" @click="open()">新增骑手</el-button></div><section class="control-card table-card"><div class="filter-row"><el-input v-model="query.keyword" :prefix-icon="Search" placeholder="搜索骑手姓名" clearable @keyup.enter="load(1)" @clear="load(1)"/><el-select v-model="query.status" clearable placeholder="全部状态" @change="load(1)"><el-option label="可接单" :value="1"/><el-option label="不可接单" :value="0"/></el-select><el-button type="primary" @click="load(1)">查询</el-button></div><el-table :data="data.records" stripe><el-table-column label="骑手" min-width="180"><template #default="{row}"><div class="rider-cell"><span>{{row.riderName.slice(0,1)}}</span><div><b>{{row.riderName}}</b><small>{{row.phone}}</small></div></div></template></el-table-column><el-table-column prop="remark" label="备注" min-width="180"><template #default="{row}">{{row.remark||'-'}}</template></el-table-column><el-table-column label="可接单" width="110"><template #default="{row}"><el-switch :model-value="row.status===1" @change="toggle(row)"/></template></el-table-column><el-table-column label="更新时间" width="170"><template #default="{row}">{{dateTime(row.updateTime)}}</template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button text type="primary" :icon="EditPen" @click="open(row)">编辑</el-button><el-button text type="danger" :icon="Delete" @click="remove(row)">删除</el-button></template></el-table-column></el-table></section><div class="pagination"><el-pagination background layout="total, prev, pager, next" :current-page="data.current" :page-size="data.size" :total="data.total" @current-change="load"/></div><el-dialog v-model="dialog" :title="editId?'编辑骑手':'新增骑手'" width="min(470px,92%)"><el-form label-position="top"><el-form-item label="骑手姓名" required><el-input v-model="form.riderName" maxlength="32"/></el-form-item><el-form-item label="手机号码" required><el-input v-model="form.phone" maxlength="11"/></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" maxlength="255"/></el-form-item><el-form-item label="可接单状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" active-text="可接单" inactive-text="不可接单"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.eyebrow{font-size:11px;color:#1677ff;letter-spacing:2px;font-weight:700}.admin-page-head h1{font-size:27px;margin:6px 0}.admin-page-head p{margin:0;color:#8491a4;font-size:13px}.filter-row .el-input{width:250px}.filter-row .el-select{width:140px}.rider-cell{display:flex;align-items:center;gap:10px}.rider-cell>span{width:38px;height:38px;border-radius:13px;background:linear-gradient(135deg,#19b98a,#6ddac1);color:#fff;display:grid;place-items:center;font-size:16px}.rider-cell b,.rider-cell small{display:block}.rider-cell b{font-size:13px}.rider-cell small{font-size:11px;color:#8b98aa;margin-top:4px}@media(max-width:650px){.filter-row .el-input{width:100%;flex-basis:100%}}</style>
