
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import { adminUserApi } from '@/api'
import type { PageData, User } from '@/types'
import { dateTime } from '@/utils'
const data=ref<PageData<User>>({records:[],current:1,size:10,total:0,pages:0});const query=reactive({page:1,size:10,keyword:'',role:'',status:undefined as number|undefined});const load=async(page=query.page)=>{query.page=page;data.value=await adminUserApi.page({...query,role:query.role||undefined})};onMounted(load)
const toggle=async(u:User)=>{if(u.role==='ADMIN'&&u.status===1){try{await ElMessageBox.confirm('禁用管理员会导致其无法登录，确认继续吗？','修改账号状态',{type:'warning'})}catch{return}}await adminUserApi.status(u.id,u.status?0:1);ElMessage.success('用户状态已更新');await load(data.value.current)}
</script>
<template><div><div class="admin-page-head"><div><span class="eyebrow">USER MANAGEMENT</span><h1>用户管理</h1><p>查看注册用户，并控制账号启用状态。角色不可在此修改。</p></div></div><section class="control-card table-card"><div class="filter-row"><el-input v-model="query.keyword" :prefix-icon="Search" placeholder="账号、昵称、手机号" clearable @keyup.enter="load(1)" @clear="load(1)"/><el-select v-model="query.role" placeholder="全部角色" clearable @change="load(1)"><el-option label="普通用户" value="USER"/><el-option label="药品管理员" value="ADMIN"/></el-select><el-select v-model="query.status" placeholder="全部状态" clearable @change="load(1)"><el-option label="启用" :value="1"/><el-option label="禁用" :value="0"/></el-select><el-button type="primary" @click="load(1)">查询</el-button></div><el-table :data="data.records" stripe><el-table-column label="用户" min-width="190"><template #default="{row}"><div class="user-cell"><el-avatar>{{row.nickname.slice(0,1)}}</el-avatar><div><b>{{row.nickname}}</b><small>账号：{{row.username}}</small></div></div></template></el-table-column><el-table-column prop="phone" label="手机号" width="145"><template #default="{row}">{{row.phone||'-'}}</template></el-table-column><el-table-column label="角色" width="125"><template #default="{row}"><el-tag :type="row.role==='ADMIN'?'primary':'success'" effect="light" round>{{row.role==='ADMIN'?'药品管理员':'普通用户'}}</el-tag></template></el-table-column><el-table-column label="账号状态" width="125"><template #default="{row}"><el-switch :model-value="row.status===1" @change="toggle(row)"/></template></el-table-column><el-table-column label="创建时间" width="175"><template #default="{row}">{{dateTime((row as any).createTime)}}</template></el-table-column></el-table></section><div class="pagination"><el-pagination background layout="total, prev, pager, next" :current-page="data.current" :page-size="data.size" :total="data.total" @current-change="load"/></div></div></template>
<style scoped>.eyebrow{font-size:11px;color:#1677ff;letter-spacing:2px;font-weight:700}.admin-page-head h1{font-size:27px;margin:6px 0}.admin-page-head p{margin:0;color:#8491a4;font-size:13px}.filter-row .el-input{width:250px}.filter-row .el-select{width:130px}.user-cell{display:flex;align-items:center;gap:10px}.user-cell .el-avatar{background:linear-gradient(135deg,#1677ff,#6dbdff)}.user-cell b,.user-cell small{display:block}.user-cell b{font-size:13px}.user-cell small{font-size:11px;color:#8b98aa;margin-top:4px}@media(max-width:650px){.filter-row .el-input{width:100%;flex-basis:100%}}</style>
