
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, EditPen, Delete, Location } from '@element-plus/icons-vue'
import { addressApi } from '@/api'
import type { Address } from '@/types'
import { fullAddress } from '@/utils'
const addresses=ref<Address[]>([]);const drawer=ref(false);const saving=ref(false);const editId=ref<number>();
const emptyForm=()=>({receiverName:'',receiverPhone:'',province:'广东省',city:'惠州市',district:'',detailAddress:'',isDefault:false});const form=reactive(emptyForm())
const load=async()=>{addresses.value=await addressApi.list()};onMounted(load)
const open=(item?:Address)=>{Object.assign(form,emptyForm());editId.value=item?.id;if(item)Object.assign(form,{...item,isDefault:item.isDefault===1});drawer.value=true}
const save=async()=>{if(!form.receiverName||!form.receiverPhone||!form.detailAddress)return ElMessage.warning('请完整填写收货人、电话和详细地址');saving.value=true;try{if(editId.value)await addressApi.update(editId.value,form);else await addressApi.add(form);ElMessage.success('地址已保存');drawer.value=false;await load()}finally{saving.value=false}}
const remove=async(id:number)=>{await ElMessageBox.confirm('确认删除该地址吗？','删除地址',{type:'warning'});await addressApi.remove(id);ElMessage.success('地址已删除');await load()}
const setDefault=async(id:number)=>{await addressApi.setDefault(id);ElMessage.success('默认地址已更新');await load()}
</script>
<template><div class="page-container address-page"><div class="page-head"><div><span class="eyebrow">DELIVERY ADDRESS</span><h1>收货地址</h1><p>维护配送地址，下单时可快速选择。</p></div><el-button type="primary" :icon="Plus" @click="open()">新增地址</el-button></div><div v-if="addresses.length" class="address-grid"><article v-for="a in addresses" :key="a.id" class="address-card" :class="{default:a.isDefault===1}"><div class="address-top"><span class="address-icon"><el-icon><Location/></el-icon></span><div><h3>{{a.receiverName}} <small>{{a.receiverPhone}}</small></h3><p>{{fullAddress(a)}}</p></div><el-tag v-if="a.isDefault===1" type="primary" effect="light" round>默认地址</el-tag></div><div class="address-actions"><el-button v-if="a.isDefault!==1" text type="primary" @click="setDefault(a.id)">设为默认</el-button><el-button text :icon="EditPen" @click="open(a)">编辑</el-button><el-button text type="danger" :icon="Delete" @click="remove(a.id)">删除</el-button></div></article></div><div v-else class="address-blank"><el-icon><Location/></el-icon><h2>还没有收货地址</h2><p>新增一个地址，方便你下单时快速选择。</p><el-button type="primary" @click="open()">新增地址</el-button></div><el-drawer v-model="drawer" :title="editId?'编辑收货地址':'新增收货地址'" size="min(480px, 100%)"><el-form label-position="top"><el-form-item label="收货人"><el-input v-model="form.receiverName" maxlength="32" placeholder="请输入收货人姓名"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.receiverPhone" maxlength="11" placeholder="请输入 11 位手机号"/></el-form-item><el-form-item label="所在地区"><div class="area-inputs"><el-input v-model="form.province" placeholder="省"/><el-input v-model="form.city" placeholder="市"/><el-input v-model="form.district" placeholder="区/县"/></div></el-form-item><el-form-item label="详细地址"><el-input v-model="form.detailAddress" type="textarea" :rows="3" maxlength="255" placeholder="例如：演示路 100 号 2 栋 301"/></el-form-item><el-form-item><el-switch v-model="form.isDefault" active-text="设为默认地址"/></el-form-item><el-button type="primary" class="drawer-save" :loading="saving" @click="save">保存地址</el-button></el-form></el-drawer></div></template>
<style scoped>.page-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:23px}.eyebrow{font-size:11px;color:#1677ff;letter-spacing:2px;font-weight:700}.page-head h1{margin:6px 0;font-size:28px}.page-head p{margin:0;color:#8090a3;font-size:13px}.address-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.address-card{background:#fff;border:1px solid #e6edf7;border-radius:15px;padding:20px;transition:.22s}.address-card:hover{transform:translateY(-3px);box-shadow:0 12px 25px rgba(21,74,138,.09)}.address-card.default{border-color:#a8d0ff;background:linear-gradient(135deg,#fff,#f5faff)}.address-top{display:flex;gap:12px;align-items:flex-start}.address-icon{width:42px;height:42px;border-radius:13px;background:#edf6ff;color:#1677ff;display:grid;place-items:center;font-size:20px}.address-top>div:nth-child(2){flex:1}.address-top h3{margin:2px 0 7px;font-size:15px}.address-top h3 small{font-size:12px;color:#8796aa;font-weight:400;margin-left:7px}.address-top p{margin:0;font-size:13px;color:#6d7d91;line-height:1.6}.address-actions{border-top:1px solid #edf1f5;padding-top:11px;margin-top:15px;display:flex;justify-content:flex-end}.address-blank{background:#fff;border:1px dashed #cddceb;border-radius:16px;text-align:center;padding:70px 20px;color:#8291a5}.address-blank .el-icon{font-size:45px;color:#a8d0ff}.address-blank h2{font-size:17px;color:#506078}.address-blank p{font-size:13px}.area-inputs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;width:100%}.drawer-save{width:100%;height:42px;border-radius:9px}@media(max-width:720px){.address-grid{grid-template-columns:1fr}.page-head{align-items:flex-start;gap:12px;flex-direction:column}.area-inputs{grid-template-columns:1fr}}</style>
