
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Delete, ShoppingCart, WarningFilled } from '@element-plus/icons-vue'
import { cartApi } from '@/api'
import { useCartStore } from '@/stores/cart'
import { money } from '@/utils'
import EmptyState from '@/components/EmptyState.vue'
const router=useRouter();const store=useCartStore();const loading=ref(false)
onMounted(async()=>{loading.value=true;try{await store.load()}finally{loading.value=false}})
const validItems=computed(()=>store.cart.items.filter(i=>i.available));const selectedIds=computed(()=>store.cart.items.filter(i=>i.selected&&i.available).map(i=>i.cartItemId))
const changeQuantity=async(id:number,value:number|undefined)=>{if(!value)return;await cartApi.quantity(id,value);await store.load()}
const changeSelected=async(id:number,value:boolean)=>{await cartApi.selected(id,value);await store.load()}
const remove=async(id:number)=>{await ElMessageBox.confirm('确认从购物车移除该商品吗？','删除商品',{type:'warning'});await cartApi.remove(id);await store.load();ElMessage.success('已删除')}
const selectAll=async(value:boolean)=>{for(const item of validItems.value.filter(i=>i.selected!==value))await cartApi.selected(item.cartItemId,value);await store.load()}
const checkout=()=>{if(!selectedIds.value.length)return ElMessage.warning('请至少选择一件可结算商品');router.push({name:'checkout',query:{ids:selectedIds.value.join(',')}})}
</script>
<template><div class="page-container cart-page"><div class="cart-head"><div><span class="eyebrow">MY CART</span><h1>购物车</h1><p>确认商品与数量后进入结算。</p></div><el-button v-if="store.cart.items.some(i=>!i.available)" text type="danger" @click="cartApi.clearInvalid().then(store.load)">清空失效商品</el-button></div><div v-loading="loading" v-if="store.cart.items.length" class="cart-layout"><section class="cart-list"><div class="cart-list-head"><el-checkbox :model-value="validItems.length>0&&validItems.every(i=>i.selected)" :indeterminate="validItems.some(i=>i.selected)&&!validItems.every(i=>i.selected)" @change="(v:boolean)=>selectAll(v)">全选</el-checkbox><span>已选 {{store.cart.selectedCount}} 件</span></div><article v-for="item in store.cart.items" :key="item.cartItemId" class="cart-row" :class="{invalid:!item.available}"><el-checkbox :model-value="item.selected" :disabled="!item.available" @change="(v:boolean)=>changeSelected(item.cartItemId,v)"/><div class="cart-image"><img v-if="item.imageUrl" :src="item.imageUrl"/><span v-else>药</span></div><div class="cart-main"><h3>{{item.medicineName}}</h3><p :class="{bad:!item.available,low:item.stock>0&&item.stock<item.quantity}">{{!item.available?'商品已失效或缺货':`库存 ${item.stock} 件`}}</p><b>{{money(item.price)}}</b></div><el-input-number :model-value="item.quantity" :min="1" :max="Math.max(1,item.stock)" :disabled="!item.available" @change="(v:number|undefined)=>changeQuantity(item.cartItemId,v)"/><strong>{{money(item.subtotalAmount)}}</strong><el-button text type="danger" :icon="Delete" @click="remove(item.cartItemId)"/></article></section><aside class="settlement"><h2>订单摘要</h2><div><span>商品合计</span><b>{{money(store.cart.selectedAmount)}}</b></div><div><span>配送费</span><b>¥5.00</b></div><div class="settle-total"><span>预估应付</span><strong>{{money(store.cart.selectedAmount+5)}}</strong></div><el-button type="primary" size="large" @click="checkout">去结算（{{selectedIds.length}}）</el-button><p><el-icon><WarningFilled/></el-icon>最终金额以提交订单时服务端计算为准。</p></aside></div><EmptyState v-else title="购物车还是空的" description="去选一些家庭常备药品吧" action-text="去选药" @action="router.push('/category')"/></div></template>
<style scoped>.cart-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.eyebrow{color:#1677ff;font-size:11px;letter-spacing:2px;font-weight:700}.cart-head h1{font-size:27px;margin:6px 0}.cart-head p{margin:0;color:#7e8da1;font-size:13px}.cart-layout{display:grid;grid-template-columns:1fr 320px;gap:20px}.cart-list,.settlement{background:#fff;border:1px solid #e6edf7;border-radius:15px}.cart-list-head{padding:16px 20px;border-bottom:1px solid #edf0f5;display:flex;justify-content:space-between;font-size:13px;color:#7b8a9f}.cart-row{padding:16px 20px;display:grid;grid-template-columns:25px 68px 1fr 110px 95px 32px;gap:15px;align-items:center;border-bottom:1px solid #f0f3f7}.cart-row:last-child{border-bottom:0}.cart-row.invalid{opacity:.58;background:#fafafa}.cart-image{width:64px;height:64px;border-radius:12px;overflow:hidden;background:#eaf5ff;display:grid;place-items:center;color:#1677ff;font-size:26px}.cart-image img{width:100%;height:100%;object-fit:cover}.cart-main h3{font-size:14px;margin:0 0 8px}.cart-main p{font-size:12px;margin:0 0 6px;color:#19b98a}.cart-main p.low{color:#ff8a34}.cart-main p.bad{color:#f04438}.cart-main b{color:#ff6d2c;font-size:16px}.cart-row>strong{color:#344054;font-size:15px;text-align:right}.settlement{height:max-content;padding:20px}.settlement h2{font-size:16px;margin:0 0 18px}.settlement>div{display:flex;justify-content:space-between;margin:13px 0;font-size:13px;color:#6d7c91}.settlement>div b{color:#344054}.settle-total{padding:16px 0;border-top:1px dashed #dbe3ed;margin-top:18px!important;align-items:end}.settle-total strong{font-size:24px;color:#ff6d2c}.settlement .el-button{width:100%;height:43px;border-radius:10px;margin-top:10px}.settlement p{color:#8a98ab;font-size:11px;line-height:1.6;display:flex;gap:4px}@media(max-width:720px){.cart-layout{grid-template-columns:1fr}.cart-row{grid-template-columns:22px 56px 1fr 32px;gap:10px;padding:14px}.cart-image{width:54px;height:54px}.cart-row>.el-input-number{grid-column:3;width:115px}.cart-row>strong{grid-column:4;grid-row:2;text-align:right}.settlement{position:sticky;bottom:12px;box-shadow:0 12px 25px rgba(0,39,90,.14)}}</style>
