
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, ShoppingCart, Lightning, WarningFilled } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { cartApi, publicApi } from '@/api'
import { useUserStore } from '@/stores/user'
import { useCartStore } from '@/stores/cart'
import type { Medicine } from '@/types'
import { money } from '@/utils'
const route=useRoute();const router=useRouter();const userStore=useUserStore();const cartStore=useCartStore();const medicine=ref<Medicine>();const quantity=ref(1);const loading=ref(false)
onMounted(async()=>{medicine.value=await publicApi.medicine(Number(route.params.id));if(medicine.value)quantity.value=1})
const ensure=()=>{if(!userStore.user){router.push({name:'login',query:{redirect:route.fullPath}});return false}return true}
const add=async(go=false)=>{if(!ensure()||!medicine.value)return;if(medicine.value.stock<=0)return ElMessage.warning('该药品暂时缺货');loading.value=true;try{await cartApi.add({medicineId:medicine.value.id,quantity:quantity.value});await cartStore.load();ElMessage.success('已加入购物车');if(go)router.push('/cart')}finally{loading.value=false}}
</script>
<template><div v-if="medicine" class="page-container detail-page"><button class="back-btn" @click="router.back()"><el-icon><ArrowLeft/></el-icon>返回商品列表</button><section class="detail-card"><div class="detail-image"><img v-if="medicine.imageUrl" :src="medicine.imageUrl" :alt="medicine.medicineName"/><span v-else>药</span><div class="image-glow"></div></div><div class="detail-info"><span class="detail-category">{{medicine.categoryName}}</span><h1>{{medicine.medicineName}}</h1><p class="detail-desc">{{medicine.description || '课程设计演示药品信息'}}</p><div class="detail-price"><span>售价</span><b>{{money(medicine.price)}}</b></div><div class="detail-stock"><span :class="{danger:medicine.stock<=0,low:medicine.isLowStock}"><i></i>{{medicine.stock<=0?'暂时缺货':medicine.isLowStock?`库存仅剩 ${medicine.stock} 件`:`库存充足，剩余 ${medicine.stock} 件`}}</span></div><div class="quantity-row"><span>购买数量</span><el-input-number v-model="quantity" :min="1" :max="Math.max(1,medicine.stock)" :disabled="medicine.stock<=0"/></div><div class="detail-actions"><el-button type="primary" size="large" :disabled="medicine.stock<=0" :loading="loading" @click="add(false)"><el-icon><ShoppingCart/></el-icon>加入购物车</el-button><el-button size="large" :disabled="medicine.stock<=0" @click="add(true)"><el-icon><Lightning/></el-icon>立即结算</el-button></div><p class="delivery-tip">下单后由管理员确认、打包并安排配送，订单状态可在“我的订单”查看。</p></div></section><section class="info-panels"><div><h2>使用说明</h2><p>{{medicine.usageInstruction || '请按商品包装说明使用。'}}</p></div><div class="warning-panel"><h2><el-icon><WarningFilled/></el-icon>注意事项</h2><p>{{medicine.precautions || '商品信息仅用于课程设计演示；如有不适请咨询专业人员。'}}</p></div></section></div></template>
<style scoped>.back-btn{border:0;background:transparent;color:#5d7491;cursor:pointer;padding:0;margin-bottom:16px;display:flex;gap:5px;align-items:center}.detail-card{background:#fff;border:1px solid #e5ecf7;border-radius:20px;padding:42px;display:grid;grid-template-columns:44% 1fr;gap:54px;box-shadow:0 13px 30px rgba(20,69,125,.06)}.detail-image{min-height:370px;border-radius:18px;background:linear-gradient(135deg,#e7f4ff,#e5fff5);position:relative;display:grid;place-items:center;overflow:hidden}.detail-image img{width:100%;height:100%;object-fit:cover;position:relative;z-index:1}.detail-image>span{width:135px;height:135px;background:#fff;border-radius:40px;display:grid;place-items:center;font-size:60px;color:#1677ff;z-index:1}.image-glow{position:absolute;width:270px;height:270px;border-radius:50%;background:rgba(255,255,255,.6);filter:blur(4px)}.detail-category{display:inline-block;background:#edf6ff;color:#1677ff;border-radius:20px;padding:5px 10px;font-size:12px}.detail-info h1{font-size:31px;margin:15px 0 10px}.detail-desc{color:#78879a;line-height:1.8;margin:0 0 24px}.detail-price{padding:17px 0;border-top:1px solid #edf0f5;border-bottom:1px solid #edf0f5;display:flex;align-items:end;gap:14px}.detail-price span{font-size:13px;color:#7d8b9e}.detail-price b{font-size:32px;color:#ff6d2c}.detail-stock{margin:17px 0;color:#19b98a;font-size:13px}.detail-stock span{display:flex;align-items:center;gap:7px}.detail-stock i{width:8px;height:8px;border-radius:50%;background:currentColor}.detail-stock .low{color:#ff8a34}.detail-stock .danger{color:#f04438}.quantity-row{display:flex;align-items:center;gap:20px;margin:22px 0}.quantity-row>span{font-size:14px;font-weight:600}.detail-actions{display:flex;gap:12px}.detail-actions .el-button{height:45px;padding:0 25px;border-radius:10px}.delivery-tip{font-size:12px;color:#8a98aa;margin-top:16px}.info-panels{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:20px}.info-panels>div{background:#fff;border:1px solid #e7edf6;border-radius:14px;padding:22px}.info-panels h2{font-size:15px;margin:0 0 10px}.info-panels p{margin:0;color:#718197;font-size:13px;line-height:1.8}.warning-panel{background:#fffaf0!important;border-color:#ffe1b3!important}.warning-panel h2{color:#d77718;display:flex;gap:5px;align-items:center}@media(max-width:720px){.detail-card{grid-template-columns:1fr;padding:20px;gap:24px}.detail-image{min-height:245px}.detail-info h1{font-size:25px}.info-panels{grid-template-columns:1fr}.detail-actions .el-button{flex:1;padding:0 8px}}</style>
