
<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Search, Filter } from '@element-plus/icons-vue'
import { publicApi } from '@/api'
import type { Category, Medicine, PageData } from '@/types'
import MedicineCard from '@/components/MedicineCard.vue'
import EmptyState from '@/components/EmptyState.vue'
const route=useRoute();const router=useRouter();const categories=ref<Category[]>([]);const result=ref<PageData<Medicine>>({records:[],current:1,size:12,total:0,pages:0});const loading=ref(false);const q=reactive({keyword:'',categoryId:undefined as number|undefined,sort:'default',page:1,size:12})
const sync=()=>{q.keyword=(route.query.keyword as string)||'';q.categoryId=route.params.id?Number(route.params.id):(route.query.categoryId?Number(route.query.categoryId):undefined);q.page=Number(route.query.page||1)}
const load=async()=>{loading.value=true;try{result.value=await publicApi.medicines(q)}finally{loading.value=false}}
const apply=()=>{router.push({name:'category',params:q.categoryId?{id:q.categoryId}: {},query:{...(q.keyword?{keyword:q.keyword}:{}),page:1}})}
const changePage=(page:number)=>router.push({name:'category',params:q.categoryId?{id:q.categoryId}: {},query:{...(q.keyword?{keyword:q.keyword}:{}),page}})
watch(()=>route.fullPath,async()=>{sync();await load()});onMounted(async()=>{categories.value=await publicApi.categories();sync();await load()})
</script>
<template><div class="page-container list-page"><div class="crumb-line"><span @click="router.push('/home')">首页</span><b>/</b><strong>{{ q.categoryId ? categories.find(c=>c.id===q.categoryId)?.categoryName || '分类药品' : '全部药品' }}</strong></div><section class="list-hero"><div><span class="eyebrow">PHARMACY CATALOG</span><h1>{{q.categoryId ? categories.find(c=>c.id===q.categoryId)?.categoryName : '发现需要的健康好物'}}</h1><p>价格、库存和可购状态实时展示，选择更有把握。</p></div><div class="hero-count"><b>{{result.total}}</b><span>在售药品</span></div></section><div class="catalog-layout"><aside class="category-side"><h3><el-icon><Filter/></el-icon>药品分类</h3><button :class="{active:!q.categoryId}" @click="router.push('/category')">全部药品</button><button v-for="c in categories" :key="c.id" :class="{active:q.categoryId===c.id}" @click="router.push(`/category/${c.id}`)"><span>{{c.categoryName}}</span><i>›</i></button></aside><main><div class="catalog-toolbar"><el-input v-model="q.keyword" clearable :prefix-icon="Search" placeholder="搜索药品名称" @keyup.enter="apply" @clear="apply"/><el-select v-model="q.sort" @change="load"><el-option label="综合排序" value="default"/><el-option label="价格从低到高" value="priceAsc"/><el-option label="价格从高到低" value="priceDesc"/><el-option label="库存优先" value="stockDesc"/></el-select><span>共 <b>{{result.total}}</b> 件商品</span></div><div v-loading="loading" class="medicine-grid"><MedicineCard v-for="m in result.records" :key="m.id" :medicine="m"/></div><EmptyState v-if="!loading&&!result.records.length" title="没有找到相关药品" description="试试更换搜索关键词或查看全部药品" action-text="查看全部" @action="router.push('/category')"/><div v-if="result.total>q.size" class="list-pagination"><el-pagination background layout="prev, pager, next" :current-page="result.current" :page-size="q.size" :total="result.total" @current-change="changePage"/></div></main></div></div></template>
<style scoped>.crumb-line{font-size:13px;color:#8a98aa;margin-bottom:16px}.crumb-line span{cursor:pointer;color:#1677ff}.crumb-line b{font-weight:400;margin:0 8px}.crumb-line strong{color:#526277}.list-hero{background:linear-gradient(130deg,#e8f4ff,#e9fff7);min-height:150px;padding:30px 36px;border-radius:18px;display:flex;justify-content:space-between;align-items:center;margin-bottom:23px;border:1px solid #dceefa}.eyebrow{color:#1677ff;font-size:11px;letter-spacing:1.6px;font-weight:700}.list-hero h1{font-size:27px;margin:8px 0}.list-hero p{font-size:13px;color:#71839a;margin:0}.hero-count{text-align:right}.hero-count b{display:block;font-size:32px;color:#1677ff}.hero-count span{font-size:12px;color:#7d8ea4}.catalog-layout{display:grid;grid-template-columns:220px 1fr;gap:20px}.category-side{background:#fff;border:1px solid #e7edf6;border-radius:14px;padding:14px;height:max-content}.category-side h3{font-size:14px;margin:4px 7px 10px;display:flex;align-items:center;gap:5px}.category-side button{border:0;background:transparent;width:100%;padding:11px 9px;border-radius:9px;text-align:left;color:#66768c;cursor:pointer;display:flex;justify-content:space-between}.category-side button.active{background:#edf5ff;color:#1677ff;font-weight:700}.category-side i{font-style:normal}.catalog-toolbar{background:#fff;border:1px solid #e7edf6;border-radius:14px;padding:12px;display:flex;align-items:center;gap:10px;margin-bottom:17px}.catalog-toolbar .el-input{max-width:320px}.catalog-toolbar .el-select{width:150px}.catalog-toolbar span{margin-left:auto;font-size:12px;color:#7b8a9f}.catalog-toolbar b{color:#1677ff}.list-pagination{display:flex;justify-content:center;margin-top:28px}@media(max-width:720px){.list-hero{padding:24px;align-items:flex-start}.hero-count{display:none}.catalog-layout{grid-template-columns:1fr}.category-side{display:flex;overflow:auto;gap:7px;padding:9px}.category-side h3{display:none}.category-side button{width:auto;white-space:nowrap}.catalog-toolbar{flex-wrap:wrap}.catalog-toolbar .el-input{max-width:none;flex-basis:100%}.catalog-toolbar span{margin-left:0}}</style>
