
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessageBox } from 'element-plus'
import { ArrowLeft, Location, Van, Memo, Money, CircleCheck } from '@element-plus/icons-vue'
import { orderApi } from '@/api'
import type { OrderDetail } from '@/types'
import { dateTime, money, orderStatusType } from '@/utils'
const route=useRoute();const router=useRouter();const order=ref<OrderDetail>();const load=async()=>order.value=await orderApi.detail(Number(route.params.id));onMounted(load)
const cancel=async()=>{if(!order.value)return;const {value}=await ElMessageBox.prompt('请输入取消原因','取消订单',{inputValidator:v=>v?true:'请输入取消原因',type:'warning'});await orderApi.cancel(order.value.id,value);await load()}
</script>
<template><div v-if="order" class="page-container order-detail"><button class="back-btn" @click="router.back()"><el-icon><ArrowLeft/></el-icon>返回订单列表</button><section class="order-status-hero"><div><span class="status-large" :class="order.orderStatus.toLowerCase()"><el-icon><CircleCheck/></el-icon></span><div><el-tag :type="orderStatusType(order.orderStatus)" round>{{order.orderStatusName}}</el-tag><h1>{{order.orderStatus==='COMPLETED'?'订单已完成':order.orderStatus==='CANCELED'?'订单已取消':'订单正在处理中'}}</h1><p>{{order.orderStatus==='DELIVERING'?'骑手已出发，请保持电话畅通。':order.orderStatus==='PENDING_ACCEPT'?'管理员将在确认后开始备货。':'订单状态更新会同步展示在下方时间线。'}}</p></div></div><div class="status-price"><span>应付金额</span><b>{{money(order.orderAmount)}}</b></div></section><div class="detail-layout"><main><section class="detail-block"><h2><el-icon><Location/></el-icon>配送地址</h2><p><b>{{order.receiverName}} {{order.receiverPhone}}</b></p><p>{{order.receiverAddress}}</p></section><section class="detail-block"><h2>商品明细</h2><article v-for="item in order.items" :key="item.id" class="item-line"><div class="item-img"><img v-if="item.medicineImage" :src="item.medicineImage"/><span v-else>药</span></div><div><b>{{item.medicineName}}</b><span>{{money(item.medicinePrice)}} × {{item.quantity}}</span></div><strong>{{money(item.subtotalAmount)}}</strong></article></section><section v-if="order.userRemark||order.adminRemark||order.cancelReason" class="detail-block"><h2><el-icon><Memo/></el-icon>订单备注</h2><p v-if="order.userRemark">用户备注：{{order.userRemark}}</p><p v-if="order.adminRemark">管理员备注：{{order.adminRemark}}</p><p v-if="order.cancelReason" class="cancel-reason">取消原因：{{order.cancelReason}}</p></section></main><aside><section v-if="order.riderName" class="detail-block rider-card"><h2><el-icon><Van/></el-icon>配送骑手</h2><div class="rider-avatar">骑</div><b>{{order.riderName}}</b><p>{{order.riderPhone}}</p></section><section class="detail-block timeline-card"><h2>订单动态</h2><el-timeline><el-timeline-item v-for="log in order.statusLogs" :key="log.id" :timestamp="dateTime(log.createTime)" :type="log.afterStatus==='CANCELED'?'danger':log.afterStatus==='COMPLETED'?'success':'primary'" hollow><b>{{log.afterStatusName}}</b><p v-if="log.remark">{{log.remark}}</p></el-timeline-item></el-timeline></section><section class="detail-block amount-card"><h2><el-icon><Money/></el-icon>费用明细</h2><div><span>商品总额</span><b>{{money(order.productAmount)}}</b></div><div><span>配送费</span><b>{{money(order.deliveryFee)}}</b></div><div class="amount-total"><span>应付金额</span><strong>{{money(order.orderAmount)}}</strong></div></section><el-button v-if="order.orderStatus==='PENDING_ACCEPT'" class="cancel-btn" type="danger" plain @click="cancel">取消订单</el-button></aside></div></div></template>
<style scoped>.back-btn{border:0;background:transparent;color:#5d7491;cursor:pointer;padding:0;margin-bottom:16px;display:flex;align-items:center;gap:5px}.order-status-hero{background:linear-gradient(130deg,#0c56a5,#1680f9);color:#fff;border-radius:18px;padding:26px 30px;display:flex;justify-content:space-between;align-items:center;box-shadow:0 14px 27px rgba(22,119,255,.18)}.order-status-hero>div:first-child{display:flex;gap:14px;align-items:center}.status-large{width:52px;height:52px;border-radius:16px;background:rgba(255,255,255,.16);display:grid;place-items:center;font-size:27px}.order-status-hero h1{font-size:21px;margin:8px 0 5px}.order-status-hero p{margin:0;color:#d8efff;font-size:12px}.status-price{text-align:right}.status-price span{display:block;font-size:12px;color:#d7ecff}.status-price b{display:block;font-size:27px;margin-top:4px}.detail-layout{display:grid;grid-template-columns:1fr 330px;gap:18px;margin-top:18px}.detail-block{background:#fff;border:1px solid #e6edf7;border-radius:14px;padding:19px;margin-bottom:16px}.detail-block h2{font-size:15px;margin:0 0 14px;display:flex;align-items:center;gap:6px}.detail-block h2 .el-icon{color:#1677ff}.detail-block>p{font-size:13px;color:#718198;line-height:1.7;margin:4px 0}.item-line{display:flex;align-items:center;gap:12px;padding:11px 0;border-bottom:1px solid #f0f3f6}.item-line:last-child{border:0}.item-img{width:47px;height:47px;border-radius:11px;background:#eaf5ff;overflow:hidden;display:grid;place-items:center;color:#1677ff}.item-img img{width:100%;height:100%;object-fit:cover}.item-line>div:nth-child(2){flex:1}.item-line b,.item-line span{display:block}.item-line b{font-size:13px}.item-line span{margin-top:5px;font-size:12px;color:#8392a5}.item-line>strong{font-size:14px}.cancel-reason{color:#ef5b4f!important}.rider-card{text-align:center}.rider-card h2{text-align:left}.rider-avatar{width:54px;height:54px;border-radius:18px;background:linear-gradient(135deg,#19b98a,#67d7bf);color:white;display:grid;place-items:center;margin:0 auto 9px;font-size:20px}.rider-card>b{font-size:15px}.rider-card p{font-size:12px}.timeline-card :deep(.el-timeline-item__timestamp){font-size:11px}.timeline-card :deep(.el-timeline-item__content){font-size:13px}.timeline-card :deep(.el-timeline-item__content p){color:#8290a4;font-size:12px;margin:4px 0}.amount-card>div{display:flex;justify-content:space-between;margin:11px 0;color:#718198;font-size:13px}.amount-card b{color:#344054}.amount-total{padding-top:13px;margin-top:15px!important;border-top:1px dashed #dbe4ed;align-items:end}.amount-total strong{color:#ff6d2c;font-size:23px}.cancel-btn{width:100%;height:40px}@media(max-width:720px){.order-status-hero{padding:20px;align-items:flex-start;gap:8px}.status-price b{font-size:20px}.detail-layout{grid-template-columns:1fr}.detail-layout aside{display:contents}.timeline-card{order:2}.amount-card{order:3}.cancel-btn{order:4;margin-top:-5px}.order-status-hero h1{font-size:17px}}</style>
