
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessageBox } from 'element-plus'
import { orderApi } from '@/api'
import type { Order, PageData, OrderStatus } from '@/types'
import { dateTime, money, orderStatusType, statusOptions } from '@/utils'
import EmptyState from '@/components/EmptyState.vue'
const router=useRouter();const status=ref<string>('');const data=ref<PageData<Order>>({records:[],current:1,size:8,total:0,pages:0});const loading=ref(false)
const load=async(page=1)=>{loading.value=true;try{data.value=await orderApi.page({page,size:8,orderStatus:status.value||undefined})}finally{loading.value=false}};onMounted(load);watch(status,()=>load(1))
const cancel=async(order:Order)=>{const {value}=await ElMessageBox.prompt('请输入取消原因','取消订单',{inputPlaceholder:'例如：暂时不需要了',inputValidator:(v)=>v?true:'请输入取消原因',type:'warning'});await orderApi.cancel(order.id,value);await load(data.value.current)}
</script>
<template><div class="page-container orders-page"><div class="page-head"><span class="eyebrow">MY ORDERS</span><h1>我的订单</h1><p>从下单到送达，关键进度都在这里。</p></div><el-tabs v-model="status" class="order-tabs"><el-tab-pane label="全部" name=""/><el-tab-pane v-for="[value,label] in statusOptions" :key="value" :label="label" :name="value"/></el-tabs><div v-loading="loading" v-if="data.records.length" class="order-list"><article v-for="order in data.records" :key="order.id" class="order-card"><div class="order-card-head"><span>订单号：<b>{{order.orderNo}}</b></span><span>{{dateTime(order.createTime)}}</span><el-tag :type="orderStatusType(order.orderStatus)" effect="light" round>{{order.orderStatusName}}</el-tag></div><div class="order-card-body"><div class="order-placeholder">药</div><div class="order-main"><h3>{{order.orderStatus==='DELIVERING'?'骑手正在配送中':order.orderStatus==='COMPLETED'?'订单已送达':'订单正在处理中'}}</h3><p>{{order.receiverAddress}}</p><small v-if="order.riderName">配送骑手：{{order.riderName}} {{order.riderPhone}}</small></div><div class="order-price"><span>订单金额</span><b>{{money(order.orderAmount)}}</b></div></div><div class="order-card-actions"><span v-if="order.userRemark">备注：{{order.userRemark}}</span><div><el-button v-if="order.orderStatus==='PENDING_ACCEPT'" plain type="danger" @click="cancel(order)">取消订单</el-button><el-button type="primary" plain @click="router.push(`/orders/${order.id}`)">查看详情</el-button></div></div></article></div><EmptyState v-else-if="!loading" title="暂时没有订单" description="选购药品并提交订单后，配送进度会显示在这里。" action-text="去选药" @action="router.push('/category')"/><div v-if="data.total>data.size" class="list-pagination"><el-pagination background layout="prev, pager, next" :current-page="data.current" :page-size="data.size" :total="data.total" @current-change="load"/></div></div></template>
<style scoped>.page-head{margin-bottom:13px}.eyebrow{color:#1677ff;font-size:11px;letter-spacing:2px;font-weight:700}.page-head h1{font-size:28px;margin:6px 0}.page-head p{font-size:13px;margin:0;color:#8190a3}.order-tabs{margin-bottom:17px}.order-list{display:grid;gap:14px}.order-card{background:#fff;border:1px solid #e6edf7;border-radius:15px;overflow:hidden;transition:.2s}.order-card:hover{box-shadow:0 11px 25px rgba(25,74,129,.09)}.order-card-head{padding:13px 18px;background:#fbfcfe;border-bottom:1px solid #edf1f5;display:flex;align-items:center;gap:16px;font-size:12px;color:#8795a8}.order-card-head b{color:#526276}.order-card-head .el-tag{margin-left:auto}.order-card-body{padding:17px 18px;display:flex;align-items:center;gap:13px}.order-placeholder{width:54px;height:54px;background:#e9f5ff;color:#1677ff;border-radius:15px;display:grid;place-items:center;font-size:24px}.order-main{flex:1}.order-main h3{font-size:14px;margin:0 0 7px}.order-main p{font-size:12px;color:#74849a;margin:0 0 5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:550px}.order-main small{color:#19b98a;font-size:11px}.order-price{text-align:right}.order-price span{display:block;color:#8a98aa;font-size:11px;margin-bottom:4px}.order-price b{font-size:18px;color:#ff6d2c}.order-card-actions{border-top:1px solid #edf1f5;padding:10px 18px;display:flex;justify-content:space-between;align-items:center;font-size:12px;color:#8694a6}.list-pagination{display:flex;justify-content:center;margin-top:26px}@media(max-width:720px){.order-card-head{gap:8px;flex-wrap:wrap}.order-card-head .el-tag{margin-left:auto}.order-card-body{align-items:flex-start}.order-main p{white-space:normal}.order-card-actions{gap:8px;align-items:flex-start;flex-direction:column}.order-card-actions>div{align-self:flex-end}}</style>
