
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { Location, Tickets, UserFilled, ArrowRight } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
const store=useUserStore();const router=useRouter()
</script>
<template><div class="page-container profile-page"><section class="profile-hero"><el-avatar :size="72" class="profile-avatar">{{store.user?.nickname?.slice(0,1)}}</el-avatar><div><span>普通用户</span><h1>{{store.user?.nickname}}</h1><p>账号：{{store.user?.username}}　{{store.user?.phone||'未绑定手机号'}}</p></div></section><section class="profile-actions"><button @click="router.push('/orders')"><span><el-icon><Tickets/></el-icon></span><div><b>我的订单</b><small>查看订单状态与配送进度</small></div><el-icon><ArrowRight/></el-icon></button><button @click="router.push('/address')"><span><el-icon><Location/></el-icon></span><div><b>收货地址</b><small>管理常用配送地址</small></div><el-icon><ArrowRight/></el-icon></button><button @click="router.push('/home')"><span><el-icon><UserFilled/></el-icon></span><div><b>继续选药</b><small>返回商城浏览药品分类</small></div><el-icon><ArrowRight/></el-icon></button></section></div></template>
<style scoped>.profile-hero{background:linear-gradient(130deg,#0d58a5,#1683ff);color:#fff;border-radius:20px;padding:34px;display:flex;align-items:center;gap:18px}.profile-avatar{background:rgba(255,255,255,.18);font-size:28px;color:#fff;border:1px solid rgba(255,255,255,.32)}.profile-hero span{font-size:12px;color:#cae7ff}.profile-hero h1{font-size:26px;margin:6px 0}.profile-hero p{font-size:13px;margin:0;color:#d7edff}.profile-actions{max-width:760px;margin:25px auto;display:grid;gap:12px}.profile-actions button{background:#fff;border:1px solid #e6edf7;border-radius:14px;text-align:left;display:flex;align-items:center;gap:14px;padding:17px;cursor:pointer;transition:.2s}.profile-actions button:hover{transform:translateY(-2px);box-shadow:0 10px 23px rgba(22,75,132,.09);border-color:#b9d8ff}.profile-actions button>span{width:42px;height:42px;border-radius:13px;background:#edf6ff;color:#1677ff;display:grid;place-items:center;font-size:20px}.profile-actions div{flex:1}.profile-actions b,.profile-actions small{display:block}.profile-actions b{font-size:14px;color:#344054}.profile-actions small{font-size:12px;color:#8492a5;margin-top:5px}.profile-actions>button>.el-icon{color:#9badc1}</style>
