
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { User, Lock, FirstAidKit, Van } from '@element-plus/icons-vue'
import { authApi } from '@/api'
import { useUserStore } from '@/stores/user'
const router=useRouter();const route=useRoute();const userStore=useUserStore();const loading=ref(false)
const form=reactive({username:'',password:''})
const submit=async()=>{if(!form.username||!form.password)return ElMessage.warning('请填写账号和密码');loading.value=true;try{const data=await authApi.login(form);userStore.setUser(data.user);userStore.initialized=true;const redirect=typeof route.query.redirect==='string'?route.query.redirect:'';router.replace(redirect||data.redirectPath)}finally{loading.value=false}}
</script>
<template><div class="auth-page"><div class="auth-visual"><div class="auth-brand"><span class="brand-mark"><FirstAidKit/></span><div><b>速安药房</b><small>PHARMACY DELIVERY</small></div></div><div class="visual-copy"><span class="visual-pill">30 分钟安心送达</span><h1>常用药品<br/><i>安心送达</i></h1><p>找药、下单、配送状态一目了然。<br/>一套为单店即时配送打造的管理系统。</p></div><div class="route-line"><span class="route-node n1"><FirstAidKit/></span><span class="route-node n2"><Van/></span><b></b></div><div class="floating-pill pill-a">库存实时同步</div><div class="floating-pill pill-b">配送状态可追踪</div></div><div class="auth-form-wrap"><div class="auth-card"><span class="eyebrow">WELCOME BACK</span><h2>欢迎回来</h2><p class="auth-sub">登录后继续你的药店服务体验</p><el-form @submit.prevent="submit"><el-form-item><el-input v-model="form.username" size="large" placeholder="请输入账号" :prefix-icon="User" @keyup.enter="submit"/></el-form-item><el-form-item><el-input v-model="form.password" size="large" type="password" show-password placeholder="请输入密码" :prefix-icon="Lock" @keyup.enter="submit"/></el-form-item><el-button class="auth-submit" type="primary" size="large" :loading="loading" @click="submit">登录系统</el-button></el-form><div class="demo-account"><b>演示账号</b><span>管理员：admin / 123456</span><span>普通用户：user01 / 123456</span></div><p class="auth-switch">还没有账号？<a @click="router.push('/register')">立即注册</a></p></div></div></div></template>
<style scoped>
.auth-page{min-height:100vh;display:grid;grid-template-columns:1.08fr .92fr;background:#fff}.auth-visual{position:relative;overflow:hidden;padding:54px clamp(40px,8vw,120px);color:#fff;background:linear-gradient(135deg,#08447f,#1677ff 54%,#48b9ff)}.auth-visual:before,.auth-visual:after{content:"";position:absolute;border-radius:50%;background:rgba(255,255,255,.08)}.auth-visual:before{width:500px;height:500px;right:-180px;top:-120px}.auth-visual:after{width:330px;height:330px;left:-160px;bottom:-100px}.auth-brand{display:flex;align-items:center;gap:10px;position:relative;z-index:1}.auth-brand b{font-size:18px;display:block}.auth-brand small{font-size:10px;letter-spacing:2px;color:#cce9ff}.visual-copy{position:relative;z-index:1;margin-top:16vh}.visual-pill{font-size:13px;background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.26);border-radius:20px;padding:7px 12px}.visual-copy h1{font-size:clamp(42px,5vw,70px);line-height:1.17;margin:24px 0 18px;letter-spacing:-2px}.visual-copy i{font-style:normal;color:#8de6ff}.visual-copy p{line-height:1.9;color:#d2e8ff}.route-line{height:150px;position:absolute;z-index:1;left:20%;right:14%;bottom:10%;border-top:2px dashed rgba(255,255,255,.58);border-radius:50%;transform:rotate(-7deg)}.route-node{position:absolute;width:54px;height:54px;border-radius:18px;display:grid;place-items:center;background:#fff;color:#1677ff;box-shadow:0 14px 30px rgba(0,36,88,.22);font-size:27px;transform:rotate(7deg)}.n1{left:-12px;top:-30px}.n2{right:-12px;top:-30px}.route-line b{position:absolute;left:48%;top:-14px;width:20px;height:20px;border-radius:50%;background:#ffcc5c}.floating-pill{position:absolute;z-index:1;border:1px solid rgba(255,255,255,.23);background:rgba(255,255,255,.12);padding:9px 13px;border-radius:12px;font-size:12px;backdrop-filter:blur(8px);animation:float 6s ease-in-out infinite}.pill-a{right:16%;top:30%}.pill-b{left:15%;bottom:22%;animation-delay:-3s}@keyframes float{50%{transform:translateY(-12px)}}.auth-form-wrap{display:grid;place-items:center;padding:36px}.auth-card{width:min(100%,430px)}.eyebrow{color:#1677ff;font-size:11px;letter-spacing:2px;font-weight:700}.auth-card h2{font-size:32px;margin:11px 0 8px}.auth-sub{color:#7c889a;margin:0 0 30px}.auth-submit{width:100%;margin-top:8px;border-radius:10px;height:46px}.demo-account{margin:22px 0;background:#f4f8ff;border:1px solid #e6effd;border-radius:12px;padding:12px 14px;font-size:12px;color:#65758a;display:grid;gap:4px}.demo-account b{color:#344054}.auth-switch{text-align:center;color:#7b889c;font-size:14px}.auth-switch a{color:#1677ff;font-weight:700;cursor:pointer}@media(max-width:820px){.auth-page{grid-template-columns:1fr}.auth-visual{min-height:250px;padding:28px}.visual-copy{margin-top:32px}.visual-copy h1{font-size:38px;margin:15px 0}.route-line,.floating-pill{display:none}.auth-form-wrap{padding:35px 24px}}
</style>
