
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { User, Lock, Phone, FirstAidKit, Van } from '@element-plus/icons-vue'
import { authApi } from '@/api'
const router=useRouter();const loading=ref(false);const form=reactive({username:'',nickname:'',phone:'',password:'',confirmPassword:''})
const submit=async()=>{if(!form.username||!form.nickname||!form.password)return ElMessage.warning('请完整填写必填信息');if(form.password.length<6)return ElMessage.warning('密码至少为 6 位');if(form.password!==form.confirmPassword)return ElMessage.warning('两次密码输入不一致');loading.value=true;try{await authApi.register(form);ElMessage.success('注册成功，请登录');router.push('/login')}finally{loading.value=false}}
</script>
<template><div class="auth-page"><div class="auth-visual"><div class="auth-brand"><span class="brand-mark"><FirstAidKit/></span><div><b>速安药房</b><small>PHARMACY DELIVERY</small></div></div><div class="visual-copy"><span class="visual-pill">新用户注册</span><h1>健康服务<br/><i>即刻开始</i></h1><p>注册成为普通用户，体验在线选药、<br/>购物车结算与即时配送流程。</p></div><div class="route-line"><span class="route-node n1"><FirstAidKit/></span><span class="route-node n2"><Van/></span><b></b></div></div><div class="auth-form-wrap"><div class="auth-card"><span class="eyebrow">CREATE ACCOUNT</span><h2>创建账号</h2><p class="auth-sub">注册后即可开始浏览和下单</p><el-form @submit.prevent="submit"><el-form-item><el-input v-model="form.username" size="large" placeholder="账号：4~32 位字母、数字或下划线" :prefix-icon="User"/></el-form-item><el-form-item><el-input v-model="form.nickname" size="large" placeholder="昵称" :prefix-icon="User"/></el-form-item><el-form-item><el-input v-model="form.phone" size="large" placeholder="手机号（选填）" :prefix-icon="Phone"/></el-form-item><el-form-item><el-input v-model="form.password" size="large" type="password" show-password placeholder="设置 6~32 位密码" :prefix-icon="Lock"/></el-form-item><el-form-item><el-input v-model="form.confirmPassword" size="large" type="password" show-password placeholder="确认密码" :prefix-icon="Lock" @keyup.enter="submit"/></el-form-item><el-button class="auth-submit" type="primary" size="large" :loading="loading" @click="submit">完成注册</el-button></el-form><p class="auth-switch">已有账号？<a @click="router.push('/login')">去登录</a></p></div></div></div></template>
<style scoped>
.auth-page{min-height:100vh;display:grid;grid-template-columns:1.08fr .92fr;background:#fff}.auth-visual{position:relative;overflow:hidden;padding:54px clamp(40px,8vw,120px);color:#fff;background:linear-gradient(135deg,#08447f,#1677ff 54%,#48b9ff)}.auth-visual:before{content:"";position:absolute;width:500px;height:500px;right:-170px;top:-150px;border-radius:50%;background:rgba(255,255,255,.08)}.auth-brand{display:flex;align-items:center;gap:10px;position:relative;z-index:1}.auth-brand b{font-size:18px;display:block}.auth-brand small{font-size:10px;letter-spacing:2px;color:#cce9ff}.visual-copy{position:relative;z-index:1;margin-top:16vh}.visual-pill{font-size:13px;background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.23);padding:7px 12px;border-radius:20px}.visual-copy h1{font-size:clamp(42px,5vw,70px);line-height:1.17;margin:24px 0 18px;letter-spacing:-2px}.visual-copy i{font-style:normal;color:#8de6ff}.visual-copy p{line-height:1.9;color:#d2e8ff}.route-line{height:150px;position:absolute;z-index:1;left:20%;right:14%;bottom:10%;border-top:2px dashed rgba(255,255,255,.58);border-radius:50%;transform:rotate(-7deg)}.route-node{position:absolute;width:54px;height:54px;border-radius:18px;display:grid;place-items:center;background:#fff;color:#1677ff;box-shadow:0 14px 30px rgba(0,36,88,.22);font-size:27px;transform:rotate(7deg)}.n1{left:-12px;top:-30px}.n2{right:-12px;top:-30px}.route-line b{position:absolute;left:48%;top:-14px;width:20px;height:20px;border-radius:50%;background:#ffcc5c}.auth-form-wrap{display:grid;place-items:center;padding:36px}.auth-card{width:min(100%,430px)}.eyebrow{color:#1677ff;font-size:11px;letter-spacing:2px;font-weight:700}.auth-card h2{font-size:32px;margin:11px 0 8px}.auth-sub{color:#7c889a;margin:0 0 30px}.auth-submit{width:100%;margin-top:8px;border-radius:10px;height:46px}.auth-switch{text-align:center;color:#7b889c;font-size:14px;margin-top:24px}.auth-switch a{color:#1677ff;font-weight:700;cursor:pointer}@media(max-width:820px){.auth-page{grid-template-columns:1fr}.auth-visual{min-height:250px;padding:28px}.visual-copy{margin-top:32px}.visual-copy h1{font-size:38px;margin:15px 0}.route-line{display:none}.auth-form-wrap{padding:35px 24px}}
</style>
